### ISSUE TITLE
Errors parsing results using docced exampl for planets

### ISSUE THREAD

**Issue by bgs1979** [prokerala/astrology-sdk#1]
`[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined property: stdClass::$id in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 54
[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined property: stdClass::$id in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 55
[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined index:  in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 55
[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined property: stdClass::$longitude in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 56
[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined property: stdClass::$is_reverse in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 57
[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined property: stdClass::$position in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 58
[Thu Oct 24 20:00:35.403369 2019] [php7:notice] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Notice:  Undefined property: stdClass::$degree in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\vendor\\prokerala\\astrology-sdk\\src\\Api\\Astrology\\Result\\Planet.php on line 59
[Thu Oct 24 20:00:35.404367 2019] [php7:error] [pid 2868:tid 1300] [client 127.0.0.1:53555] PHP Fatal error:  Uncaught Error: Cannot use object of type Prokerala\\Api\\Astrology\\Result\\Planet as array in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\index.php:91\nStack trace:\n#0 {main}\n  thrown in C:\\dev\\www\\bfclocal\\public_html\\mooncalc\\index.php on line 91
`

**Comment by JoyceBabu** [comment]
@bgs1979 This should be fixed in the master branch.

**Comment by JoyceBabu** [comment]
Closing the issue as resolved.
